[package]
name = "day4"
version = "0.1.0"
authors = ["Douglas Camata <dcamata@newrelic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
verex = "0.2"
regex = "1"
