name: Rust (build and test)

on:
  push:
    branches: [ main ]
    paths: 
      - 'rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./rust
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./rust
      run: cargo test --verbose
